#!/bin/sh

set -e

##### Install programs #####
sudo add-apt-repository ppa:git-core/ppa
sudo add-apt-repository ppa:neovim-ppa/unstable
sudo apt-get update
sudo apt-get install neofetch
sudo apt-get install git
sudo apt-get install neovim
sudo apt-get install gcc

##### Command line configs #####
git config --global core.filemode false
git config --global push.autoSetupRemote true
git config --global user.name "Zach Gharst"
git config --global user.email "zdgharst@gmail.com"
git config --global init.defaultBranch "main"

##### Add RC symbolic links #####
git pull origin master
ln -sf "$PWD/.bashrc" "$HOME/.bashrc"
ln -sf "$PWD/.inputrc" "$HOME/.inputrc"
ln -sf "$PWD/.tmux.conf" "$HOME/.tmux.conf"
ln -sf "$PWD/.vimrc" "$HOME/.vimrc"
ln -sf "$PWD/nvim" "$HOME/.config/nvim"

##### Install Go #####
sudo rm -rf /usr/local/go
wget https://go.dev/dl/go1.20.5.linux-amd64.tar.gz
sudo tar -C /usr/local -xzf go1.20.5.linux-amd64.tar.gz
rm go1.20.5.linux-amd64.tar.gz

##### Install Go programs #####
go install github.com/rwxrob/pomo/cmd/pomo@latest
pomo init
pomo delete interval

go install github.com/zachgharst/emojimaker@latest
go install github.com/zachghars/gittake@latest

##### Neovim #####
git clone --depth 1 https://github.com/wbthomason/packer.nvim\
 ~/.local/share/nvim/site/pack/packer/start/packer.nvim

# how to do :PackerSync vim command?
