#!/usr/bin/env bash

function install_powershell() {
    source /etc/os-release

    url="https://packages.microsoft.com/config/ubuntu/$VERSION_ID/packages-microsoft-prod.deb"
    echo "Downloading Microsoft PPA from $url"
    wget -q $url

    sudo dpkg -i packages-microsoft-prod.deb
    rm packages-microsoft-prod.deb

    sudo apt-get update
    sudo apt-get install -y powershell

    mkdir -p "$HOME/.config/powershell" || true
    ln -sf "$PWD/Microsoft.PowerShell_profile.ps1" "$HOME/.config/powershell/Microsoft.PowerShell_profile.ps1"
}

function install_programs() {
    sudo apt update
    sudo apt install -y wslu

    install_powershell
}

function configure_git() {
    git config --global credential.helper "/mnt/c/Program\ Files/Git/mingw64/bin/git-credential-manager.exe"
}

function add_config_files() {
    ln -sf "$PWD/.bashrc.wsl" "$HOME/.bashrc.wsl"
}

install_programs
configure_git
add_config_files
