local trouble = require('trouble')
vim.keymap.set('n', '<leader>wx', function() trouble.toggle() end)
vim.keymap.set('n', '<leader>ww', function() trouble.toggle('workspace_diagnostics') end)
vim.keymap.set('n', '<leader>wd', function() trouble.toggle('document_diagnostics') end)
vim.keymap.set('n', '<leader>wq', function() trouble.toggle('quickfix') end)
vim.keymap.set('n', '<leader>wl', function() trouble.toggle('loclist') end)
vim.keymap.set('n', 'gR', function() trouble.toggle('lsp_references') end)
